- name: Ensure folders exist
  file:
    path: "/home/pi/{{ item }}"
    state: directory
    owner: pi
    group: pi
  with_items:
    - .kenban
    - .config

- name: Remove deprecated parameter "listen"
  lineinfile:
    regexp: '^.*listen.*'
    state: absent
    dest: /home/pi/.kenban/kenban.conf

- name: Install pip dependencies
  pip:
    requirements: /home/pi/kenban/requirements/requirements.host.txt
    extra_args: "--no-cache-dir --upgrade"

- name: Remove kenban_utils.sh
  file:
    state: absent
    path: /usr/local/bin/kenban_utils.sh

- cron:
    name: Cleanup kenban_assets
    state : absent
    user: pi

- name: Download upgrade_kenban.sh from github repository
  get_url:
    url: https://raw.githubusercontent.com/Kenban/kenban_os/master/bin/install.sh
    dest: /usr/local/sbin/upgrade_kenban.sh
    mode: 0700
    owner: root
    group: root
    force: yes

- name: Copy kenban_overrides
  copy:
    src: kenban_overrides
    dest: /etc/sudoers.d/kenban_overrides
    mode: 0440
    owner: root
    group: root

- name: Installs autoplay udev rule
  copy:
    src: 50-autoplay.rules
    dest: /etc/udev/rules.d/50-autoplay.rules
    mode: 644
    owner: root
    group: root

- name: Copy systemd-udevd service
  copy:
    src: /lib/systemd/system/systemd-udevd.service
    dest: /etc/systemd/system/systemd-udevd.service

- name: Configure systemd-udevd service
  lineinfile:
    dest: /etc/systemd/system/systemd-udevd.service
    regexp: '^MountFlags='
    line: 'MountFlags=shared'

- name: Create udev-restart service
  copy:
    src: "udev-restart.service"
    dest: "/etc/systemd/system/udev-restart.service"

- name: Remove plymouth-quit-wait.service
  file:
    state: absent
    dest: /lib/systemd/system/plymouth-quit-wait.service

- name: Remove plymouth-quit.service
  file:
    state: absent
    dest: /lib/systemd/system/plymouth-quit.service

- name: Enable kenban systemd services
  command: systemctl enable udev-restart.service chdir=/etc/systemd/system

