version: "2"
services:
  server:
    image: kenban/server-kos
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    environment:
      - HOME=/data
      - LISTEN=0.0.0.0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    devices:
      - "/dev/vchiq:/dev/vchiq"
    restart: always
    volumes:
      - kenban-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      io.balena.features.supervisor-api: '1'

  viewer:
    image: kenban/viewer-kos
    build:
      context: .
      dockerfile: docker/Dockerfile.viewer
    mem_limit: ${VIEWER_MEMORY_LIMIT_KB}k
    shm_size: '1gb'
    depends_on:
      - server
    environment:
      #- WEBVIEW_DEBUG=true
      - HOME=/data
      - PORT=80
      - NOREFRESH=1
      - LISTEN=nginx
    privileged: true
    restart: always
    volumes:
      - kenban-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  celery:
    image: kenban/celery-kos
    build:
      context: .
      dockerfile: docker/Dockerfile.celery
    depends_on:
      - server
      - redis
    environment:
      - HOME=/data
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    devices:
      - "/dev/vchiq:/dev/vchiq"
    restart: always
    volumes:
      - kenban-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  redis:
    image: kenban/redis-kos
    build:
      context: .
      dockerfile: docker/Dockerfile.redis
    ports:
      - 127.0.0.1:6379:6379
    restart: always
    volumes:
      - redis-data:/var/lib/redis

  nginx:
    image: kenban/nginx-kos
    build:
      context: .
      dockerfile: docker/Dockerfile.nginx
    environment:
      - HOME=/data
    depends_on:
      - server
    restart: always
    volumes:
      - kenban-data:/data:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  websocket:
    image: kenban/websocket-kos
    build:
      context: .
      dockerfile: docker/Dockerfile.websocket
    environment:
      - HOME=/data
    depends_on:
      - server
    restart: always
    volumes:
      - kenban-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

volumes:
  kenban-data:
  redis-data:
