version: "2"
services:
  kb-os-server:
    image: kenban/kb-os-server:${DOCKER_TAG}
    environment:
      - MY_IP=${MY_IP}
    volumes:
      - /home/pi/.screenly:/data/.screenly
      - /home/pi/screenly_assets:/data/screenly_assets
      - /home/pi/screenly/static:/data/screenly/static
      - /home/pi/kenban_assets:/data/kenban_assets
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  kb-os-viewer:
    image: kenban/kb-os-viewer:${DOCKER_TAG}-${DEVICE_TYPE}
    mem_limit: ${VIEWER_MEMORY_LIMIT_KB}k
    volumes:
      - /home/pi/.screenly:/data/.screenly
      - /home/pi/screenly_assets:/data/screenly_assets
      - /home/pi/kenban_assets:/data/kenban_assets
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  kb-os-websocket:
    image: kenban/kb-os-websocket:${DOCKER_TAG}
    volumes:
      - /home/pi/.screenly:/data/.screenly
      - /home/pi/screenly_assets:/data/screenly_assets
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  kb-os-celery:
    image: kenban/kb-os-celery:${DOCKER_TAG}
    volumes:
      - /home/pi/.screenly:/data/.screenly
      - /home/pi/screenly_assets:/data/screenly_assets
      - /home/pi/kenban_assets:/data/kenban_assets
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  redis:
    image: kenban/kb-os-redis:${DOCKER_TAG}

  kb-os-nginx:
    image: kenban/kb-os-nginx:${DOCKER_TAG}
    volumes:
      - /home/pi/.screenly:/data/.screenly:ro
      - /home/pi/screenly_assets:/data/screenly_assets:ro
      - /home/pi/screenly/static:/data/screenly/static:ro
      - /home/pi/kenban_assets:/data/kenban_assets:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

volumes:
    screenly-data:
