version: "2"
services:
  kb-os-server:
    image: kenban/kb-os-server
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    environment:
      - HOME=/data
      - LISTEN=0.0.0.0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    devices:
      - "/dev/vchiq:/dev/vchiq"
    restart: always
    volumes:
      - resin-data:/data
    labels:
      io.balena.features.supervisor-api: '1'

  kb-os-viewer:
    image: kenban/kb-os-viewer
    build:
      context: .
      dockerfile: docker/Dockerfile.viewer
    depends_on:
      - kb-os-server
    environment:
      - HOME=/data
      - PORT=80
      - NOREFRESH=1
      - LISTEN=kb-os-nginx
    privileged: true
    restart: always
    volumes:
      - resin-data:/data

  kb-os-celery:
    image: kenban/kb-os-celery
    build:
      context: .
      dockerfile: docker/Dockerfile.celery
    depends_on:
      - kb-os-server
      - redis
    environment:
      - HOME=/data
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    devices:
      - "/dev/vchiq:/dev/vchiq"
    restart: always
    volumes:
      - resin-data:/data

  redis:
    image: kenban/kb-os-redis
    build:
      context: .
      dockerfile: docker/Dockerfile.redis
    ports:
      - 127.0.0.1:6379:6379
    restart: always
    volumes:
      - redis-data:/var/lib/redis

  kb-os-nginx:
    image: kenban/kb-os-nginx
    build:
      context: .
      dockerfile: docker/Dockerfile.nginx
    ports:
      - 80:80
    environment:
      - HOME=/data
    depends_on:
      - kb-os-server
    restart: always
    volumes:
      - resin-data:/data:ro

  kb-os-kbsync:
    image: kenban/kb-os-kbsync
    build:
      context: .
      dockerfile: docker/Dockerfile.kbsync
    environment:
      - HOME=/data
    depends_on:
      - kb-os-server
    restart: always
    volumes:
      - resin-data:/data

volumes:
    resin-data:
    redis-data:
