# ansible playbook
---
- name: Update
  hosts: localhost
  become: true

  tasks:

    - name: git pull
      command:
        cmd: git pull
        chdir: '/home/user/kenban'

    - name: Schedule system reboot at 3am
      command: "shutdown -r 03:00"
      become: yes

    - name: Record last update timestamp
      lineinfile:
        path: /var/log/kenban_update.log
        line: "Update run: {{ ansible_date_time.iso8601 }}"
        insertafter: EOF
        create: yes
        mode: "0644"
        owner: root
        group: root
