# ansible playbook
---
- name: Update
  hosts: localhost
  remote_user: pi
  become: true

  tasks:
    - name: Update nginx to 1.18.0
      apt:
        name: nginx=1.18.0
        state: present
        update_cache: yes

