# ansible playbook
---
- name: Update
  hosts: localhost
  remote_user: root
  become: true
  become_method: sudo

  tasks:
    - name: Update nginx to 1.18.0
      apt:
        name: nginx=1.18.0
        state: present
        update_cache: yes

