# ansible playbook
---
- name: Update
  hosts: localhost
  become: true

  tasks:
    - name: Update nginx to latest
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Update redis
      pip:
        name: redis==4.4.0