# ansible playbook
---
- name: Update
  hosts: localhost
  become: true

  tasks:
    - name: Update nginx to latest
      apt:
        name: nginx=1.18.0
        state: present
        update_cache: yes

