# ansible playbook
---
- name: Update
  hosts: localhost
  become: true

  tasks:

    - name: Update repository
      git:
        repo: 'https://github.com/kenban/kenban_os.git'
        dest: '/home/user/kenban'
        update: yes

    - name: Schedule system reboot at 3am
      command: "shutdown -r 03:00"
      become: yes