- name: Add pi user to Identity
  replace:
    regexp: '^Identity=.*'
    replace: 'Identity=unix-group:netdev;unix-group:sudo:pi'
    dest: /var/lib/polkit-1/localauthority/10-vendor.d/org.freedesktop.NetworkManager.pkla


- name: Set ResultAny to yes
  replace:
    regexp: '^ResultAny=.*'
    replace: 'ResultAny=yes'
    dest: /var/lib/polkit-1/localauthority/10-vendor.d/org.freedesktop.NetworkManager.pkla


- name: Copy org.freedesktop.NetworkManager.pkla to 50-local.d
  command: cp -f /var/lib/polkit-1/localauthority/10-vendor.d/org.freedesktop.NetworkManager.pkla /etc/polkit-1/localauthority/50-local.d


- name: Disable dhcpcd
  command: systemctl disable dhcpcd


- name: Activate NetworkManager
  command: systemctl enable NetworkManager


- name: Add wifi manager service
  copy:
    src: "kenban-wifi-manager.service"
    dest: "/etc/systemd/system/kenban-wifi-manager.service"

- name: Activate Kenban wifi manager
  command: systemctl enable kenban-wifi-manager
